### ISSUE TITLE
[BUG] False-negative result for the rule "An element's IsOffScreen property must be false when its clickable point is on screen."

### ISSUE THREAD

**Issue by lennyomg** [microsoft/axe-windows#352] opened 2020-04-10 20:31 UTC
## Issue

False-negative result for the rule "An element's IsOffScreen property must be false when its clickable point is on screen."

Using WPF .NET 4.6.1 all hidden controls have false-negative results regarding IsOffscreen==True and ClickablePoint. It happens because, in spite of the fact that WPF returns IsOffScreen==True, it also returns some value for ClickablePoint.

According to [MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.automationelement.automationelementinformation.isoffscreen?view=netframework-4.8):
> If the element has a clickable point that can cause it to be focused, it is considered to be onscreen even when a portion of the element is off screen. 

The main thing in the statement above is "that **can cause** it to be focused". But there is no way how an element can be focused if it is hidden. So, I see an incorrect implementation of this rule.

## To Reproduce
```
<Window x:Class="IsOffscreenIssue.MainWindow" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="d" Title="MainWindow"
        Height="450" Width="800">
    <StackPanel>
        <Button Content="btn 1" />
        <Button Content="btn 2" Visibility="Collapsed" />
    </StackPanel>
</Window>
```
## Expected behavior

Accessibility Insight tool mustn't report that error for hidden elements.

## Actual behavior

Accessibility Insight tool reports that error for hidden elements.

## Screenshots or .GIF

![image](https://user-images.githubusercontent.com/1433092/79020672-51d75500-7b2e-11ea-8d3b-ed3dd8f35b74.png)

## Desktop

 - OS: Windows 10 1303
 - Accessibility Insights for Windows Version: 1.1.1152.1

## Additional context

Related issue: #162

**Comment by RobGallo** [comment] 2020-04-13 21:15
@lennyomg

Thanks for filing this bug. We agree this is a false positive because it is possible for a UIA element to have a valid ClickablePoint property and yet not be visible on screen.

**Comment by dominoFire** [comment] 2020-04-23 04:02
How those changes are reflected in Accessibility Insights for Windows (AI)? I have a similar issue, but with a custom, always-collapsed TextBlock control. Also, I can confirm that a collapsed button is not flagged by AI.

Relevant code:

```xml
      <!--
        Special TextBlock to report loading status to assistive technologies (narrator).
        Code behind changes to the Text property will trigger a narrator event.
      -->
      <vs:LiveTextBlock
        x:Name="_ltbLoading"
        Visibility="Collapsed"
        IsFrequencyLimited="True"
        Focusable="False"
        AutomationProperties.IsOffscreenBehavior="Offscreen"
        />

      <Button Focusable="False" Visibility="Collapsed" x:Name="_testAxe" />
```

Screenshot

![image](https://user-images.githubusercontent.com/1192347/80055942-d5525800-84d7-11ea-923b-ecfceb6e3c1a.png)

LiveTest:

![image](https://user-images.githubusercontent.com/1192347/80055630-febeb400-84d6-11ea-80c1-3a5865e7800c.png)

Properties:

![image](https://user-images.githubusercontent.com/1192347/80057757-48f66400-84dc-11ea-9bd3-8be5dc98fe0f.png)

**Comment by RobGallo** [comment] 2020-04-23 14:22
@dominoFire 
After the fix, the rule will not be run on elements which are not focusable.

This fix has not yet made it into AI-Win. Once the next version of axe-windows is released, the fix will be brought into the canary version of AI-Win. We will release a new version of axe-windows soon. Thanks for your patience.

**Comment by DaveTryon** [comment] 2020-04-28 21:48
@dominoFire, this fix is now available in the Canary channel of AIWin. Please use the settings page to change to the Canary channel and regress. Marking as resolved on our end.

**Comment by dominoFire** [comment] 2020-05-04 18:30
> @dominoFire, @lennyomg, this fix is now available in the Canary channel of AIWin. Please use the settings page to change to the Canary channel and regress. Marking as resolved on our end.

Thank you! I've verified that my collapsed textbox is not flagged in the 1.1.1214.1 build

**Closed** 2020-05-06 13:49 UTC
Labels: bug, status: needs author feedback, status: no recent activity, status: resolved
