### ISSUE TITLE
[BUG] axe-windows not reporting UIA Patterns for some elements

### ISSUE THREAD

**Issue by jalkire** [microsoft/axe-windows#283] opened 2020-01-22 00:51 UTC
## Describe the bug
AI-Win fails to report patterns for certain elements for which Inspect shows patterns. The problem probably resides in axe-windows, not AI-Win.

**To Reproduce**

1. Open "Edit local users and groups"
2. Invoke the "Users" row in the center list
3. Point AI-Win (run it as admin) at any of the cells in the "Name" row
4. Observe that there are no available patterns in AI-Win

## Expected behavior
If you point Inspect at the same cell, you can see GridItemPattern, LegacyIAccessiblePattern, TableItemPattern are supported and their properties are displayed.

## Actual behavior
AI-Win displays no patterns.

## Screenshots or .GIF
![image](https://user-images.githubusercontent.com/4615491/72855865-c906f680-3c6d-11ea-865e-2f68339abcf6.png)

## Desktop (please complete the following information):

 - OS: Windows 10 1909
 - Accessibility Insights for Windows Version: 1.1.1107.1 (and others)
 - Target Application: MMC

**Comment by jalkire** [comment] 2020-03-12 15:47
Handing off to the expert @RobGallo

**Comment by RobGallo** [comment] 2020-03-12 22:10
This issue had the same root cause as issue #320 , which was resolved by PR #321 .

**Comment by RobGallo** [comment] 2020-03-23 17:47
Fixed in 0.9.1.

**Closed by RobGallo** 2020-03-23 17:47 UTC
Labels: bug, status: resolved
